[package]
name = "ORM_RUST"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
mongodb = "2.8.2"
serde = "1.0.198"
serde_json = "1.0.79" 
tokio = "1.37.0"

